### ISSUE TITLE
Fatal error: Interface 'GraphQL\Type\DefinitionContainer' not found 

### ISSUE THREAD

**Issue by heavybeard** [BE-Webdesign/wp-graphql#154]
Hello, thanks for your plugin, but i cannot test it because i received this fatal error message:

`Fatal error: Interface 'GraphQL\Type\DefinitionContainer' not found in /var/www/wordpresssite/wp-content/plugins/wp-graphql/src/Type/BaseType.php on line 16`

I've installed and activated your plugin with `php wp-cli-phar plugin install https://github.com/BE-Webdesign/wp-graphql/archive/master.zip --activate`

I've launched `composer install` inside the plugin folder

At last i went to http://wordpressite.local/graphql and I received the previous fatal error message

**Comment by heavybeard** [comment]
This Fatal Error happened with master version, but with develop version everything is ok.

**Comment by BE-Webdesign** [comment]
Yeah, not everything has been pushed to master, I reccomend checking out https://github.com/wp-graphql/wp-graphql instead as this repo is no longer active.
